fix exception specifier clash for c++11
Avoids the following error:
/usr/include/c++/4.8/new:98:41: error: declaration of ‘void operator
delete [](void*) noexcept (true)’ has a different exception specifier

include/ucommon/cpr.h:170:13: error: from previous declaration ‘void
    operator delete [](void*)’